name: Newman
on: [push]
jobs:
    Newman:
        name: API testing with Postman/Newman
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v1
            with:
              node-version: "14.x"
          - run: npm install
          - run: npm run api-test
